### ISSUE TITLE
Not working with FF 48 Beta3

### ISSUE THREAD

**Issue by kilara1988** [Mardak/enterSelects#11]
Just updated to FF 48 Beta 3 and it seems they finally removed the about:config pref browser.urlbar.unifiedcomplete and your addon stopped working.
1.If the pref is removed - the addon no longer selects any entry.
2.If the pref is manually created and set to false - the addon selects the first non "Search with"/"visit" entry,but after a browser restart it selects the "Search with"/"visit" entries and hitting enter doesn't do anything.
3.If the pref is manually created and set to true - the addon properly selects the first non "Search with"/"visit" entry and still works after a browser restart.

So it seems that if the pref is not present(which is the default now) or manually created and set to false(which no longer works) the addon doesn't work properly or at all.

v13 of the addon states that it is supposed to be compatible with the pref no longer existing in FF 49+.
Maybe it doesn't work for me with the pref not existing because i am still using FF48?
Will it "magically" start working for me(with non existing pref) when i update to FF49?

This was tested with v13 of the addon.

**Comment by Mardak** [comment]
Ah, I believe the issue is that you previously set the pref that no longer exists. The add-on is using your set pref value even though it should actually be ignored as the behavior is always unified = true.

**Comment by Mardak** [comment]
This was caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1279425
